'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funzionalità di salvataggio automatico My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Z:\Modpack\Log.txt")>  _
        Public Property FileLogPath() As String
            Get
                Return CType(Me("FileLogPath"),String)
            End Get
            Set
                Me("FileLogPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1048576")>  _
        Public Property MaxLengthLog() As Long
            Get
                Return CType(Me("MaxLengthLog"),Long)
            End Get
            Set
                Me("MaxLengthLog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("normal")>  _
        Public Property LogType() As String
            Get
                Return CType(Me("LogType"),String)
            End Get
            Set
                Me("LogType") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=Z:\ModPack\ModPackDB.mdf;Inte"& _ 
            "grated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property ModPackDBConnectionString() As String
            Get
                Return CType(Me("ModPackDBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property FormatoStampa() As Global.System.Drawing.Printing.PageSettings
            Get
                Return CType(Me("FormatoStampa"),Global.System.Drawing.Printing.PageSettings)
            End Get
            Set
                Me("FormatoStampa") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("110")>  _
        Public Property Etichette_DimensioneX() As Integer
            Get
                Return CType(Me("Etichette_DimensioneX"),Integer)
            End Get
            Set
                Me("Etichette_DimensioneX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("69")>  _
        Public Property Etichette_DimensioneY() As Integer
            Get
                Return CType(Me("Etichette_DimensioneY"),Integer)
            End Get
            Set
                Me("Etichette_DimensioneY") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property Etichette_MargineTop() As Integer
            Get
                Return CType(Me("Etichette_MargineTop"),Integer)
            End Get
            Set
                Me("Etichette_MargineTop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property Etichette_MargineBottom() As Integer
            Get
                Return CType(Me("Etichette_MargineBottom"),Integer)
            End Get
            Set
                Me("Etichette_MargineBottom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property Etichette_MargineLeft() As Integer
            Get
                Return CType(Me("Etichette_MargineLeft"),Integer)
            End Get
            Set
                Me("Etichette_MargineLeft") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property Etichette_MargineRight() As Integer
            Get
                Return CType(Me("Etichette_MargineRight"),Integer)
            End Get
            Set
                Me("Etichette_MargineRight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\10.0.0.5\TSC TTP-246M Pro")>  _
        Public Property Etichette_Stampante() As String
            Get
                Return CType(Me("Etichette_Stampante"),String)
            End Get
            Set
                Me("Etichette_Stampante") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CK_ConfermaEvaso() As Boolean
            Get
                Return CType(Me("CK_ConfermaEvaso"),Boolean)
            End Get
            Set
                Me("CK_ConfermaEvaso") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OrdiniAperti_ColoraScaduti() As Boolean
            Get
                Return CType(Me("OrdiniAperti_ColoraScaduti"),Boolean)
            End Get
            Set
                Me("OrdiniAperti_ColoraScaduti") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OrdiniAperti_ColoraEvasi() As Boolean
            Get
                Return CType(Me("OrdiniAperti_ColoraEvasi"),Boolean)
            End Get
            Set
                Me("OrdiniAperti_ColoraEvasi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CheckInserimentoImballo() As Boolean
            Get
                Return CType(Me("CheckInserimentoImballo"),Boolean)
            End Get
            Set
                Me("CheckInserimentoImballo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StampaBarcodeDistinte() As Boolean
            Get
                Return CType(Me("StampaBarcodeDistinte"),Boolean)
            End Get
            Set
                Me("StampaBarcodeDistinte") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property StampaBarcodeSoloCodice() As Boolean
            Get
                Return CType(Me("StampaBarcodeSoloCodice"),Boolean)
            End Get
            Set
                Me("StampaBarcodeSoloCodice") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property DimensioneFontDistinta() As Integer
            Get
                Return CType(Me("DimensioneFontDistinta"),Integer)
            End Get
            Set
                Me("DimensioneFontDistinta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property NumeroRigheDistinta() As String
            Get
                Return CType(Me("NumeroRigheDistinta"),String)
            End Get
            Set
                Me("NumeroRigheDistinta") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property LimiteTavole8() As Integer
            Get
                Return CType(Me("LimiteTavole8"),Integer)
            End Get
            Set
                Me("LimiteTavole8") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Z:\ModPack\ModPackConfig.xml")>  _
        Public Property XMLpath() As String
            Get
                Return CType(Me("XMLpath"),String)
            End Get
            Set
                Me("XMLpath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NO_REPLY@bicciatoserafino.com")>  _
        Public Property MAIL_username() As String
            Get
                Return CType(Me("MAIL_username"),String)
            End Get
            Set
                Me("MAIL_username") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("estate-2016")>  _
        Public Property MAIL_password() As String
            Get
                Return CType(Me("MAIL_password"),String)
            End Get
            Set
                Me("MAIL_password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.bicciatoserafino.com")>  _
        Public Property MAIL_server() As String
            Get
                Return CType(Me("MAIL_server"),String)
            End Get
            Set
                Me("MAIL_server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property MAIL_port() As String
            Get
                Return CType(Me("MAIL_port"),String)
            End Get
            Set
                Me("MAIL_port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
        Public Property GiorniMantenimentoBackup() As Integer
            Get
                Return CType(Me("GiorniMantenimentoBackup"),Integer)
            End Get
            Set
                Me("GiorniMantenimentoBackup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Z:\ModPack\")>  _
        Public Property Root() As String
            Get
                Return CType(Me("Root"),String)
            End Get
            Set
                Me("Root") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files (x86)\Microsoft Office\Office12\Excel.exe")>  _
        Public Property ExcelPath() As String
            Get
                Return CType(Me("ExcelPath"),String)
            End Get
            Set
                Me("ExcelPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ListaNuoviExcel() As Boolean
            Get
                Return CType(Me("ListaNuoviExcel"),Boolean)
            End Get
            Set
                Me("ListaNuoviExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Developer() As Boolean
            Get
                Return CType(Me("Developer"),Boolean)
            End Get
            Set
                Me("Developer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Scarto() As Integer
            Get
                Return CType(Me("Scarto"),Integer)
            End Get
            Set
                Me("Scarto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MisurePari() As Boolean
            Get
                Return CType(Me("MisurePari"),Boolean)
            End Get
            Set
                Me("MisurePari") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ArrL5() As Boolean
            Get
                Return CType(Me("ArrL5"),Boolean)
            End Get
            Set
                Me("ArrL5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("011111010100000011101")>  _
        Public Property FiltroColonneImballi() As String
            Get
                Return CType(Me("FiltroColonneImballi"),String)
            End Get
            Set
                Me("FiltroColonneImballi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ImballiNRecords() As Integer
            Get
                Return CType(Me("ImballiNRecords"),Integer)
            End Get
            Set
                Me("ImballiNRecords") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property OrdiniNRecords() As Integer
            Get
                Return CType(Me("OrdiniNRecords"),Integer)
            End Get
            Set
                Me("OrdiniNRecords") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nuovo Utente")>  _
        Public Property Utente() As String
            Get
                Return CType(Me("Utente"),String)
            End Get
            Set
                Me("Utente") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NoteDinamico() As Boolean
            Get
                Return CType(Me("NoteDinamico"),Boolean)
            End Get
            Set
                Me("NoteDinamico") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0011011111111010010000000010")>  _
        Public Property FiltroColonneOrdini() As String
            Get
                Return CType(Me("FiltroColonneOrdini"),String)
            End Get
            Set
                Me("FiltroColonneOrdini") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TestoIconeMain() As Boolean
            Get
                Return CType(Me("TestoIconeMain"),Boolean)
            End Get
            Set
                Me("TestoIconeMain") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DialogConfrontoIndici() As Boolean
            Get
                Return CType(Me("DialogConfrontoIndici"),Boolean)
            End Get
            Set
                Me("DialogConfrontoIndici") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property NumeroOrdineClipboard() As Boolean
            Get
                Return CType(Me("NumeroOrdineClipboard"),Boolean)
            End Get
            Set
                Me("NumeroOrdineClipboard") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ModPack.My.MySettings
            Get
                Return Global.ModPack.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
